### ISSUE TITLE
CUDA out of memory problem in external hard drive (Ubuntu 22.04, RTX 3090)

### ISSUE THREAD

**Issue by EmissiveSlider** [jantic/DeOldify#439]
Didn't know if its because its from an external hard drive connected to the usb port or version compatibility problems of my pytorch and cuda.

**Comment by EmissiveSlider** [comment]
Turns out it is the external that decreases the performance of the GPU so I will just lower the render factor.
