### ISSUE TITLE
Having trouble trying to colorize and save a single image..

### ISSUE THREAD

**Issue by jdc4429** [jantic/DeOldify#472]
Hey Jason,

Unfortunately I am having another issue trying to colorize a single image and save it.  I've spent about 6 hours trying to figure this out because I didn't want to take up your time again but I am stumped.  I even asked GPT-4 and Sage (Cool free bot's at poe.com FYI) Every suggestion the AI bot's make is wrong.. I've tried getting them to fix like 5 times. lol  I think it is still referencing your older releases.  I don't want to use plot (Don't want to have to be in jupyter) and that seems to be where all the examples of single image colorizations are.
I'm trying to use 'colorizer = get_image_colorizer(artistic=True/False)' and
colorized_image = colorizer.get_transformed_image(input_image)
But I keep getting read errors.. I tried changing out the read library with import os and the OpenAI open_image library but they all fail.  The file paths are good and I can colorize the image I believe just not save it!

The error is:

Traceback (most recent call last):
  File "/home/jeff/DeOldify/colorize_it.py", line 27, in <module>
    colorized_image = colorizer.get_transformed_image(input_image)
  File "/home/jeff/DeOldify/deoldify/visualize.py", line 173, in get_transformed_image
    orig_image = self._open_pil_image(path)
  File "/home/jeff/DeOldify/deoldify/visualize.py", line 58, in _open_pil_image
    return PIL.Image.open(path).convert('RGB')
  File "/home/jeff/anaconda3/lib/python3.10/site-packages/PIL/Image.py", line 3236, in open
    prefix = fp.read(16)
  File "/home/jeff/anaconda3/lib/python3.10/site-packages/PIL/Image.py", line 529, in __getattr__
    raise AttributeError(name)
AttributeError: read

Here is the broken code, if you could please tell me what I'm doing wrong...
Also I could not find a reference to explain the different modules and their functions.

from deoldify import device
from deoldify.device_id import DeviceId
from pathlib import Path
import fastai
device.set(device=DeviceId.GPU0)   
from deoldify.visualize import *
import torch
import glob
if not torch.cuda.is_available():
    print('GPU not available.')
import warnings
warnings.filterwarnings("ignore", category=UserWarning, message=".*?Your .*? set is empty.*?")
colorizer = get_image_colorizer(artistic=True)
render_factor=21
source_url=None
source_path="/home/jeff/Real-ESRGAN/out_frames/"
result_path=None
input_path = Path('/home/jeff/Real-ESRGAN/out_frames/test.jpg')
print(f"input_path exists: {input_path.exists()}")
input_image = Image.open(input_path)
colorized_image = colorizer.get_transformed_image(input_image)
results_dir = Path('/home/jeff/Real-ESRGAN/col_frames/')
colorizer._save_result_image(input_path, colorized_image, results_dir)
print("Passed the single image")

Regards,

Jeff

**Comment by jdc4429** [comment]
I think it may be related to the source file type. Seems to fail (and delete the video) before saving the audio from source.  Does the colorizer only work with the mp4 extension? Do you know what audio formats are supported as well as video?

**Comment by jantic** [comment]
Sorry about the delay.  This one should be a pretty easy fix- don't pass in input_image to colorizer.get_transformed_image.  Pass input_path instead. The function takes a path, not an image.  Hope that didn't suck up too much more time!

**Comment by jdc4429** [comment]
Thanks Jason.  I am still having an issue saving the file.  I don't see any
documentation on how to call these things and no example I can find that
uses this function. The examples just plot the image and say to right click
and save as..

Here is sample code..

input_path = '/home/jeff/DeOldify/test_images/00104.jpg'
result = colorizer.get_transformed_image(input_path, render_factor)  #
Original line, idea to try below line
output_file = 'home/jeff/DeOldify/result_images/'
colorizer._save_result_image(output_file, image = result)   #<--- Don't
know what I need to pass.
print("Passed the single image")

How do I pass to colorizer._save_result_image() ?

Thanks again.

Regards,
Jeff

**Comment by jdc4429** [comment]
Thanks for the info, I did not know that the _ meant not public facing or
have forgotten. I actually tried that way but I got an error. :(

Traceback (most recent call last):
  File "/home/jeff/DeOldify/colorize_it.py", line 27, in <module>
    colorizer._save_result_image(input_path, result)
  File "/home/jeff/DeOldify/deoldify/visualize.py", line 164, in
_save_result_image
    result_path = results_dir / source_path.name
AttributeError: 'str' object has no attribute 'name'


In case you're curious, I basically want to be able to do this so I can try
using the Artistic method on a video.  Problems with the red getting washed
out and still get frames with hands that are gray or part of the head when
wearing a hat.
I want to see if I can get better results.. Plus I can add upscalers and
such... There is a really good upscaler now that has some really good face
restoration.  Unfortunately it's not good on the side or back of the head
yet.  But if the face is head on the results are amazing. It's called
GFPGAN and can be found on github. Version 1.4 is the best so far. You can
take a jpg of a whole person that's only around 200x250 and crop the head
only to 512x512.  It's scary good.
Any idea on the error?

**Comment by jdc4429** [comment]
Nevermind, I got it working.  removed the .name from the visualize.py and
it works.

Thanks a lot for your time.  Will let you know the results if you like.

Regards,

Jeff

**Comment by jantic** [comment]
Awesome!

**Comment by jdc4429** [comment]
Hey Jason,

Just wanted to give you an update.  I was trying to use the artistic feature for video which I did do successfully but it seems to have more issues with leaving gray parts.. like the nose... It's too bad because it seems to give more yellows and possibly better reds.  Deciding on reds and creating that red fog seems to be the biggest issue.  And second biggest would be the parts that still have a gray tone to them.. usually things like hands or shaded faces.  I found it really makes a difference in quality when you have a better quality video to start.  Some shows the color is amazing.  Others with lower film resolution and quality (like 360p) are not as good.  If you are looking for more results to compare, I have the B&W and color versions for 35 shows I am colorizing.  I believe you already subscribed (@jdc4429 - Jeff's Classics + The Bird Cam)

**Comment by jantic** [comment]
> I found it really makes a difference in quality when you have a better quality video to start

Yeah that's definitely something I've found and have advised users in the past to consider. And unfortunately this is even true with my later and more fancy commercial versions of this stuff. It was improved upon quite a bit, but ultimately it's just inherently harder for the AI to work with poor quality images/video.

>  I have 2 GPU's running 24/7 colorizing. lol

WOW! This is great to hear.
