### ISSUE TITLE
NVIDIA driver problem when run ImageColorizerStableTests

### ISSUE THREAD

**Issue by MaxLin86** [jantic/DeOldify#92]
When I update latest DeOldify and run ImageColorizerStableTests, error occurs at the beginning that "from fasterai.visualize import *":

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-89bddd11dfc9> in <module>
----> 1 from fasterai.visualize import *
      2 plt.style.use('dark_background')

~/ly18/deoldify/fasterai/visualize.py in <module>
      5 from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
      6 from .filters import IFilter, MasterFilter, ColorizerFilter
----> 7 from .generators import gen_inference_deep, gen_inference_wide
      8 from tensorboardX import SummaryWriter
      9 from scipy import misc

~/ly18/deoldify/fasterai/generators.py in <module>
     14       return learn
     15 
---> 16 def gen_learner_wide(data:ImageDataBunch, gen_loss=FeatureLoss(), arch=models.resnet101, nf_factor:int=2)->Learner:
     17     return unet_learner_wide(data, arch=arch, wd=1e-3, blur=True, norm_type=NormType.Spectral,
     18                         self_attention=True, y_range=(-3.,3.), loss_func=gen_loss, nf_factor=nf_factor)

~/ly18/deoldify/fasterai/loss.py in __init__(self, layer_wgts)
     10         super().__init__()
     11 
---> 12         self.m_feat = models.vgg16_bn(True).features.cuda().eval()
     13         requires_grad(self.m_feat, False)
     14         blocks = [i-1 for i,o in enumerate(children(self.m_feat)) if isinstance(o,nn.MaxPool2d)]

/opt/conda/envs/deoldify/lib/python3.7/site-packages/torch/nn/modules/module.py in cuda(self, device)
    258             Module: self
    259         """
--> 260         return self._apply(lambda t: t.cuda(device))
    261 
    262     def cpu(self):

/opt/conda/envs/deoldify/lib/python3.7/site-packages/torch/nn/modules/module.py in _apply(self, fn)
    185     def _apply(self, fn):
    186         for module in self.children():
--> 187             module._apply(fn)
    188 
    189         for param in self._parameters.values():

/opt/conda/envs/deoldify/lib/python3.7/site-packages/torch/nn/modules/module.py in _apply(self, fn)
    191                 # Tensors stored in modules are graph leaves, and we don't
    192                 # want to create copy nodes, so we have to unpack the data.
--> 193                 param.data = fn(param.data)
    194                 if param._grad is not None:
    195                     param._grad.data = fn(param._grad.data)

/opt/conda/envs/deoldify/lib/python3.7/site-packages/torch/nn/modules/module.py in <lambda>(t)
    258             Module: self
    259         """
--> 260         return self._apply(lambda t: t.cuda(device))
    261 
    262     def cpu(self):

/opt/conda/envs/deoldify/lib/python3.7/site-packages/torch/cuda/__init__.py in _lazy_init()
    159         raise RuntimeError(
    160             "Cannot re-initialize CUDA in forked subprocess. " + msg)
--> 161     _check_driver()
    162     torch._C._cuda_init()
    163     _cudart = _load_cudart()

/opt/conda/envs/deoldify/lib/python3.7/site-packages/torch/cuda/__init__.py in _check_driver()
     89 Alternatively, go to: https://pytorch.org to install
     90 a PyTorch version that has been compiled with your version
---> 91 of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion())))
     92 
     93 

AssertionError: 
The NVIDIA driver on your system is too old (found version 9000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.
```

I wonder if any way to avoid this problem, THX.

SYSTEM ENV:ubuntu 16, Nvidia GTX1080TI driver 384.111

**Comment by jantic** [comment]
So first question is:  Did you use the conda install for DeOldify?  If not, what did you do?

**Comment by MaxLin86** [comment]
Yes， I use commands you provided on "easy install".
```
git clone https://github.com/jantic/DeOldify.git DeOldify
cd DeOldify
conda env create -f environment.yml
source activate deoldify
jupyter lab
```

**Comment by jantic** [comment]
It looks like you'll have to try to install a later NVidia driver then per the error:

> The NVIDIA driver on your system is too old (found version 9000).
> Please update your GPU driver by downloading and installing a new
> version from the URL: http://www.nvidia.com/Download/index.aspx

I'm using the 410 drivers (open source)

**Comment by MaxLin86** [comment]
Right, the problem was gone when I update my NVIDIA driver.
